name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev
      - name: Version check
        run: rustc --version && cargo --version && rustfmt --version && cargo clippy --version
      - name: Format
        run: cargo fmt -- --check
      - name: Check
        run: cargo check
      - name: Clippy
        run: cargo clippy -- -D warnings
      - name: Test
        run: cargo test
      - name: Broken docs
        run: RUSTDOCFLAGS="-D warnings" cargo doc --no-deps --offline
